name: CI - Build & Push

on:
  push:
    branches:
      - "**"   # реагируем на коммиты во все ветки

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/test-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare meta (short SHA, branch)
        id: meta
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          SANITIZED_BRANCH="${GITHUB_REF_NAME//\//-}"
          echo "BRANCH=${SANITIZED_BRANCH}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:sha-${{ steps.meta.outputs.SHORT_SHA }}
            ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.BRANCH }}-latest
          # хотим latest только для main:
          # 注意: следующий блок добавит latest ТОЛЬКО если ветка main
          provenance: false
      - name: Tag latest for main branch
        if: github.ref_name == 'main'
        run: |
          docker build -t $IMAGE_NAME:latest .
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push $IMAGE_NAME:latest
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
